// manifest.js — GENERATED by tools/build-manifest.mjs. Do not hand-edit.
window.SITE = {
  "title": "Fellowship of the Heart",
  "subtitle": "CCA Pilot",
  "envLabel": "DEV",
  "license": {
    "label": "CC BY-SA 4.0",
    "url": "https://creativecommons.org/licenses/by-sa/4.0/"
  },
  "repo": "https://github.com/jgtittle-ministries/fellowship-of-the-heart-pilot-at-cca-dev"
};

window.SERIES = [
  {
    "id": "index",
    "kind": "page",
    "name": "Home",
    "path": "docs/index.md"
  },
  {
    "id": "start-here",
    "kind": "page",
    "name": "Start here",
    "path": "docs/start-here.md"
  },
  {
    "id": "getting-started",
    "kind": "series",
    "name": "Getting Started",
    "folder": "docs/getting-started",
    "edition": "v3",
    "index": "docs/getting-started/index.md",
    "chapters": [
      {
        "path": "docs/getting-started/index.md",
        "title": "Getting Started"
      },
      {
        "path": "docs/getting-started/handbook.md",
        "title": "Companion Handbook"
      },
      {
        "path": "docs/getting-started/precohort-discernment-guide.md",
        "title": "Pre-Cohort Discernment Guide"
      },
      {
        "path": "docs/getting-started/week-01-welcome.md",
        "title": "Week 1 — Welcome to the Journey"
      },
      {
        "path": "docs/getting-started/week-02-soil.md",
        "title": "Week 2 — The Soil of Your Heart"
      },
      {
        "path": "docs/getting-started/week-03-story.md",
        "title": "Week 3 — Telling Your Story"
      },
      {
        "path": "docs/getting-started/week-04-known.md",
        "title": "Week 4 — Knowing and Being Known"
      },
      {
        "path": "docs/getting-started/week-05-brave.md",
        "title": "Week 5 — Safe and Brave Together"
      },
      {
        "path": "docs/getting-started/week-06-proapt.md",
        "title": "Week 6 — Hearing God in Scripture"
      },
      {
        "path": "docs/getting-started/week-07-garden.md",
        "title": "Week 7 — The Garden of Your Heart"
      },
      {
        "path": "docs/getting-started/week-08-doubts.md",
        "title": "Week 8 — Any Doubts?"
      },
      {
        "path": "docs/getting-started/week-09-mission.md",
        "title": "Week 9 — What Was Prepared for You"
      },
      {
        "path": "docs/getting-started/week-10-sending.md",
        "title": "Week 10 — Sending and Blessing"
      },
      {
        "path": "docs/getting-started/CHANGELOG.md",
        "title": "Change Log"
      }
    ]
  },
  {
    "id": "going-deeper",
    "kind": "series",
    "name": "Going Deeper",
    "folder": "docs/going-deeper",
    "edition": "v2",
    "index": "docs/going-deeper/index.md",
    "chapters": [
      {
        "path": "docs/going-deeper/index.md",
        "title": "Going Deeper"
      },
      {
        "path": "docs/going-deeper/handbook.md",
        "title": "Companion Handbook"
      },
      {
        "path": "docs/going-deeper/week-01-welcome-back.md",
        "title": "Week 1 — Welcome Back"
      },
      {
        "path": "docs/going-deeper/week-02-soils.md",
        "title": "Week 2 — The Soils Re-Examined"
      },
      {
        "path": "docs/going-deeper/week-03-knots.md",
        "title": "Week 3 — Knots and Lies"
      },
      {
        "path": "docs/going-deeper/week-04-co-processing.md",
        "title": "Week 4 — Co-Processing in the Room"
      },
      {
        "path": "docs/going-deeper/week-05-confession.md",
        "title": "Week 5 — Confession and Restoration, Deepened"
      },
      {
        "path": "docs/going-deeper/week-06-proapt.md",
        "title": "Week 6 — PROAPT, Extended"
      },
      {
        "path": "docs/going-deeper/week-07-corporate-listening.md",
        "title": "Week 7 — Corporate Listening Prayer"
      },
      {
        "path": "docs/going-deeper/week-08-group-hears-itself.md",
        "title": "Week 8 — What the Group Hears About Itself"
      },
      {
        "path": "docs/going-deeper/week-09-shadow-mission.md",
        "title": "Week 9 — The Shadow Mission"
      },
      {
        "path": "docs/going-deeper/week-10-calling-discernment.md",
        "title": "Week 10 — Calling Discernment, Acts 13"
      },
      {
        "path": "docs/going-deeper/week-11-where-is-our-cohort.md",
        "title": "Week 11 — Where Is Our Cohort"
      },
      {
        "path": "docs/going-deeper/week-12-sending-and-bridge.md",
        "title": "Week 12 — Sending and Bridge"
      },
      {
        "path": "docs/going-deeper/CHANGELOG.md",
        "title": "Change Log"
      }
    ]
  },
  {
    "id": "going-out",
    "kind": "series",
    "name": "Going Out",
    "folder": "docs/going-out",
    "edition": "v3",
    "index": "docs/going-out/index.md",
    "chapters": [
      {
        "path": "docs/going-out/index.md",
        "title": "Going Out"
      },
      {
        "path": "docs/going-out/handbook.md",
        "title": "Companion Handbook"
      },
      {
        "path": "docs/going-out/inviting-others-handbook.md",
        "title": "Inviting Others Handbook"
      },
      {
        "path": "docs/going-out/week-01-welcome-back.md",
        "title": "Week 1 — Welcome Back — Returning to the Sent Body"
      },
      {
        "path": "docs/going-out/week-02-body-sent.md",
        "title": "Week 2 — What It Means to Be Sent"
      },
      {
        "path": "docs/going-out/week-03-where-sent.md",
        "title": "Week 3 — Where Am I Being Sent"
      },
      {
        "path": "docs/going-out/week-04-daily-tells.md",
        "title": "Week 4 — The Daily Tells"
      },
      {
        "path": "docs/going-out/week-05-household.md",
        "title": "Week 5 — The Household Witness"
      },
      {
        "path": "docs/going-out/week-06-vocational.md",
        "title": "Week 6 — The Vocational Witness"
      },
      {
        "path": "docs/going-out/week-07-third-place.md",
        "title": "Week 7 — The Third-Place Network"
      },
      {
        "path": "docs/going-out/week-08-discernment.md",
        "title": "Week 8 — Specific Missional Engagement"
      },
      {
        "path": "docs/going-out/week-09-body-sent-beyond.md",
        "title": "Week 9 — The Body Sent Beyond"
      },
      {
        "path": "docs/going-out/week-10-what-going-out-produced.md",
        "title": "Week 10 — What Going Out Produced"
      },
      {
        "path": "docs/going-out/week-11-cohort-lands.md",
        "title": "Week 11 — Where the Cohort Lands as a Body"
      },
      {
        "path": "docs/going-out/week-12-long-obedience.md",
        "title": "Week 12 — Sending Into the Long Obedience"
      },
      {
        "path": "docs/going-out/CHANGELOG.md",
        "title": "Change Log"
      }
    ]
  },
  {
    "id": "shared",
    "kind": "series",
    "name": "Shared materials",
    "folder": "docs/shared",
    "edition": null,
    "index": "docs/shared/index.md",
    "chapters": [
      {
        "path": "docs/shared/index.md",
        "title": "Shared participant materials"
      },
      {
        "path": "docs/shared/family-conversation-cards.md",
        "title": "Family Conversation Cards"
      },
      {
        "path": "docs/shared/interrogating-reality-card.md",
        "title": "Interrogating Reality Card"
      },
      {
        "path": "docs/shared/personal-heart-journal.md",
        "title": "Personal Heart Journal"
      },
      {
        "path": "docs/shared/proapt-card.md",
        "title": "PROAPT Card"
      },
      {
        "path": "docs/shared/reading-list.md",
        "title": "Reading List"
      },
      {
        "path": "docs/shared/rhythm-card.md",
        "title": "Rhythm Card"
      }
    ]
  }
];

window.PATH_TO_INFO = {
  "docs/index.md": {
    "seriesId": "index",
    "seriesName": "Home",
    "title": "Home",
    "indexPath": "docs/index.md"
  },
  "docs/start-here.md": {
    "seriesId": "start-here",
    "seriesName": "Start here",
    "title": "Start here",
    "indexPath": "docs/start-here.md"
  },
  "docs/getting-started/index.md": {
    "seriesId": "getting-started",
    "seriesName": "Getting Started",
    "edition": "v3",
    "title": "Getting Started",
    "indexPath": "docs/getting-started/index.md",
    "next": "docs/getting-started/handbook.md"
  },
  "docs/getting-started/handbook.md": {
    "seriesId": "getting-started",
    "seriesName": "Getting Started",
    "edition": "v3",
    "title": "Companion Handbook",
    "indexPath": "docs/getting-started/index.md",
    "prev": "docs/getting-started/index.md",
    "next": "docs/getting-started/precohort-discernment-guide.md"
  },
  "docs/getting-started/precohort-discernment-guide.md": {
    "seriesId": "getting-started",
    "seriesName": "Getting Started",
    "edition": "v3",
    "title": "Pre-Cohort Discernment Guide",
    "indexPath": "docs/getting-started/index.md",
    "prev": "docs/getting-started/handbook.md",
    "next": "docs/getting-started/week-01-welcome.md"
  },
  "docs/getting-started/week-01-welcome.md": {
    "seriesId": "getting-started",
    "seriesName": "Getting Started",
    "edition": "v3",
    "title": "Week 1 — Welcome to the Journey",
    "indexPath": "docs/getting-started/index.md",
    "prev": "docs/getting-started/precohort-discernment-guide.md",
    "next": "docs/getting-started/week-02-soil.md"
  },
  "docs/getting-started/week-02-soil.md": {
    "seriesId": "getting-started",
    "seriesName": "Getting Started",
    "edition": "v3",
    "title": "Week 2 — The Soil of Your Heart",
    "indexPath": "docs/getting-started/index.md",
    "prev": "docs/getting-started/week-01-welcome.md",
    "next": "docs/getting-started/week-03-story.md"
  },
  "docs/getting-started/week-03-story.md": {
    "seriesId": "getting-started",
    "seriesName": "Getting Started",
    "edition": "v3",
    "title": "Week 3 — Telling Your Story",
    "indexPath": "docs/getting-started/index.md",
    "prev": "docs/getting-started/week-02-soil.md",
    "next": "docs/getting-started/week-04-known.md"
  },
  "docs/getting-started/week-04-known.md": {
    "seriesId": "getting-started",
    "seriesName": "Getting Started",
    "edition": "v3",
    "title": "Week 4 — Knowing and Being Known",
    "indexPath": "docs/getting-started/index.md",
    "prev": "docs/getting-started/week-03-story.md",
    "next": "docs/getting-started/week-05-brave.md"
  },
  "docs/getting-started/week-05-brave.md": {
    "seriesId": "getting-started",
    "seriesName": "Getting Started",
    "edition": "v3",
    "title": "Week 5 — Safe and Brave Together",
    "indexPath": "docs/getting-started/index.md",
    "prev": "docs/getting-started/week-04-known.md",
    "next": "docs/getting-started/week-06-proapt.md"
  },
  "docs/getting-started/week-06-proapt.md": {
    "seriesId": "getting-started",
    "seriesName": "Getting Started",
    "edition": "v3",
    "title": "Week 6 — Hearing God in Scripture",
    "indexPath": "docs/getting-started/index.md",
    "prev": "docs/getting-started/week-05-brave.md",
    "next": "docs/getting-started/week-07-garden.md"
  },
  "docs/getting-started/week-07-garden.md": {
    "seriesId": "getting-started",
    "seriesName": "Getting Started",
    "edition": "v3",
    "title": "Week 7 — The Garden of Your Heart",
    "indexPath": "docs/getting-started/index.md",
    "prev": "docs/getting-started/week-06-proapt.md",
    "next": "docs/getting-started/week-08-doubts.md"
  },
  "docs/getting-started/week-08-doubts.md": {
    "seriesId": "getting-started",
    "seriesName": "Getting Started",
    "edition": "v3",
    "title": "Week 8 — Any Doubts?",
    "indexPath": "docs/getting-started/index.md",
    "prev": "docs/getting-started/week-07-garden.md",
    "next": "docs/getting-started/week-09-mission.md"
  },
  "docs/getting-started/week-09-mission.md": {
    "seriesId": "getting-started",
    "seriesName": "Getting Started",
    "edition": "v3",
    "title": "Week 9 — What Was Prepared for You",
    "indexPath": "docs/getting-started/index.md",
    "prev": "docs/getting-started/week-08-doubts.md",
    "next": "docs/getting-started/week-10-sending.md"
  },
  "docs/getting-started/week-10-sending.md": {
    "seriesId": "getting-started",
    "seriesName": "Getting Started",
    "edition": "v3",
    "title": "Week 10 — Sending and Blessing",
    "indexPath": "docs/getting-started/index.md",
    "prev": "docs/getting-started/week-09-mission.md",
    "next": "docs/getting-started/CHANGELOG.md"
  },
  "docs/getting-started/CHANGELOG.md": {
    "seriesId": "getting-started",
    "seriesName": "Getting Started",
    "edition": "v3",
    "title": "Change Log",
    "indexPath": "docs/getting-started/index.md",
    "prev": "docs/getting-started/week-10-sending.md"
  },
  "docs/going-deeper/index.md": {
    "seriesId": "going-deeper",
    "seriesName": "Going Deeper",
    "edition": "v2",
    "title": "Going Deeper",
    "indexPath": "docs/going-deeper/index.md",
    "next": "docs/going-deeper/handbook.md"
  },
  "docs/going-deeper/handbook.md": {
    "seriesId": "going-deeper",
    "seriesName": "Going Deeper",
    "edition": "v2",
    "title": "Companion Handbook",
    "indexPath": "docs/going-deeper/index.md",
    "prev": "docs/going-deeper/index.md",
    "next": "docs/going-deeper/week-01-welcome-back.md"
  },
  "docs/going-deeper/week-01-welcome-back.md": {
    "seriesId": "going-deeper",
    "seriesName": "Going Deeper",
    "edition": "v2",
    "title": "Week 1 — Welcome Back",
    "indexPath": "docs/going-deeper/index.md",
    "prev": "docs/going-deeper/handbook.md",
    "next": "docs/going-deeper/week-02-soils.md"
  },
  "docs/going-deeper/week-02-soils.md": {
    "seriesId": "going-deeper",
    "seriesName": "Going Deeper",
    "edition": "v2",
    "title": "Week 2 — The Soils Re-Examined",
    "indexPath": "docs/going-deeper/index.md",
    "prev": "docs/going-deeper/week-01-welcome-back.md",
    "next": "docs/going-deeper/week-03-knots.md"
  },
  "docs/going-deeper/week-03-knots.md": {
    "seriesId": "going-deeper",
    "seriesName": "Going Deeper",
    "edition": "v2",
    "title": "Week 3 — Knots and Lies",
    "indexPath": "docs/going-deeper/index.md",
    "prev": "docs/going-deeper/week-02-soils.md",
    "next": "docs/going-deeper/week-04-co-processing.md"
  },
  "docs/going-deeper/week-04-co-processing.md": {
    "seriesId": "going-deeper",
    "seriesName": "Going Deeper",
    "edition": "v2",
    "title": "Week 4 — Co-Processing in the Room",
    "indexPath": "docs/going-deeper/index.md",
    "prev": "docs/going-deeper/week-03-knots.md",
    "next": "docs/going-deeper/week-05-confession.md"
  },
  "docs/going-deeper/week-05-confession.md": {
    "seriesId": "going-deeper",
    "seriesName": "Going Deeper",
    "edition": "v2",
    "title": "Week 5 — Confession and Restoration, Deepened",
    "indexPath": "docs/going-deeper/index.md",
    "prev": "docs/going-deeper/week-04-co-processing.md",
    "next": "docs/going-deeper/week-06-proapt.md"
  },
  "docs/going-deeper/week-06-proapt.md": {
    "seriesId": "going-deeper",
    "seriesName": "Going Deeper",
    "edition": "v2",
    "title": "Week 6 — PROAPT, Extended",
    "indexPath": "docs/going-deeper/index.md",
    "prev": "docs/going-deeper/week-05-confession.md",
    "next": "docs/going-deeper/week-07-corporate-listening.md"
  },
  "docs/going-deeper/week-07-corporate-listening.md": {
    "seriesId": "going-deeper",
    "seriesName": "Going Deeper",
    "edition": "v2",
    "title": "Week 7 — Corporate Listening Prayer",
    "indexPath": "docs/going-deeper/index.md",
    "prev": "docs/going-deeper/week-06-proapt.md",
    "next": "docs/going-deeper/week-08-group-hears-itself.md"
  },
  "docs/going-deeper/week-08-group-hears-itself.md": {
    "seriesId": "going-deeper",
    "seriesName": "Going Deeper",
    "edition": "v2",
    "title": "Week 8 — What the Group Hears About Itself",
    "indexPath": "docs/going-deeper/index.md",
    "prev": "docs/going-deeper/week-07-corporate-listening.md",
    "next": "docs/going-deeper/week-09-shadow-mission.md"
  },
  "docs/going-deeper/week-09-shadow-mission.md": {
    "seriesId": "going-deeper",
    "seriesName": "Going Deeper",
    "edition": "v2",
    "title": "Week 9 — The Shadow Mission",
    "indexPath": "docs/going-deeper/index.md",
    "prev": "docs/going-deeper/week-08-group-hears-itself.md",
    "next": "docs/going-deeper/week-10-calling-discernment.md"
  },
  "docs/going-deeper/week-10-calling-discernment.md": {
    "seriesId": "going-deeper",
    "seriesName": "Going Deeper",
    "edition": "v2",
    "title": "Week 10 — Calling Discernment, Acts 13",
    "indexPath": "docs/going-deeper/index.md",
    "prev": "docs/going-deeper/week-09-shadow-mission.md",
    "next": "docs/going-deeper/week-11-where-is-our-cohort.md"
  },
  "docs/going-deeper/week-11-where-is-our-cohort.md": {
    "seriesId": "going-deeper",
    "seriesName": "Going Deeper",
    "edition": "v2",
    "title": "Week 11 — Where Is Our Cohort",
    "indexPath": "docs/going-deeper/index.md",
    "prev": "docs/going-deeper/week-10-calling-discernment.md",
    "next": "docs/going-deeper/week-12-sending-and-bridge.md"
  },
  "docs/going-deeper/week-12-sending-and-bridge.md": {
    "seriesId": "going-deeper",
    "seriesName": "Going Deeper",
    "edition": "v2",
    "title": "Week 12 — Sending and Bridge",
    "indexPath": "docs/going-deeper/index.md",
    "prev": "docs/going-deeper/week-11-where-is-our-cohort.md",
    "next": "docs/going-deeper/CHANGELOG.md"
  },
  "docs/going-deeper/CHANGELOG.md": {
    "seriesId": "going-deeper",
    "seriesName": "Going Deeper",
    "edition": "v2",
    "title": "Change Log",
    "indexPath": "docs/going-deeper/index.md",
    "prev": "docs/going-deeper/week-12-sending-and-bridge.md"
  },
  "docs/going-out/index.md": {
    "seriesId": "going-out",
    "seriesName": "Going Out",
    "edition": "v3",
    "title": "Going Out",
    "indexPath": "docs/going-out/index.md",
    "next": "docs/going-out/handbook.md"
  },
  "docs/going-out/handbook.md": {
    "seriesId": "going-out",
    "seriesName": "Going Out",
    "edition": "v3",
    "title": "Companion Handbook",
    "indexPath": "docs/going-out/index.md",
    "prev": "docs/going-out/index.md",
    "next": "docs/going-out/inviting-others-handbook.md"
  },
  "docs/going-out/inviting-others-handbook.md": {
    "seriesId": "going-out",
    "seriesName": "Going Out",
    "edition": "v3",
    "title": "Inviting Others Handbook",
    "indexPath": "docs/going-out/index.md",
    "prev": "docs/going-out/handbook.md",
    "next": "docs/going-out/week-01-welcome-back.md"
  },
  "docs/going-out/week-01-welcome-back.md": {
    "seriesId": "going-out",
    "seriesName": "Going Out",
    "edition": "v3",
    "title": "Week 1 — Welcome Back — Returning to the Sent Body",
    "indexPath": "docs/going-out/index.md",
    "prev": "docs/going-out/inviting-others-handbook.md",
    "next": "docs/going-out/week-02-body-sent.md"
  },
  "docs/going-out/week-02-body-sent.md": {
    "seriesId": "going-out",
    "seriesName": "Going Out",
    "edition": "v3",
    "title": "Week 2 — What It Means to Be Sent",
    "indexPath": "docs/going-out/index.md",
    "prev": "docs/going-out/week-01-welcome-back.md",
    "next": "docs/going-out/week-03-where-sent.md"
  },
  "docs/going-out/week-03-where-sent.md": {
    "seriesId": "going-out",
    "seriesName": "Going Out",
    "edition": "v3",
    "title": "Week 3 — Where Am I Being Sent",
    "indexPath": "docs/going-out/index.md",
    "prev": "docs/going-out/week-02-body-sent.md",
    "next": "docs/going-out/week-04-daily-tells.md"
  },
  "docs/going-out/week-04-daily-tells.md": {
    "seriesId": "going-out",
    "seriesName": "Going Out",
    "edition": "v3",
    "title": "Week 4 — The Daily Tells",
    "indexPath": "docs/going-out/index.md",
    "prev": "docs/going-out/week-03-where-sent.md",
    "next": "docs/going-out/week-05-household.md"
  },
  "docs/going-out/week-05-household.md": {
    "seriesId": "going-out",
    "seriesName": "Going Out",
    "edition": "v3",
    "title": "Week 5 — The Household Witness",
    "indexPath": "docs/going-out/index.md",
    "prev": "docs/going-out/week-04-daily-tells.md",
    "next": "docs/going-out/week-06-vocational.md"
  },
  "docs/going-out/week-06-vocational.md": {
    "seriesId": "going-out",
    "seriesName": "Going Out",
    "edition": "v3",
    "title": "Week 6 — The Vocational Witness",
    "indexPath": "docs/going-out/index.md",
    "prev": "docs/going-out/week-05-household.md",
    "next": "docs/going-out/week-07-third-place.md"
  },
  "docs/going-out/week-07-third-place.md": {
    "seriesId": "going-out",
    "seriesName": "Going Out",
    "edition": "v3",
    "title": "Week 7 — The Third-Place Network",
    "indexPath": "docs/going-out/index.md",
    "prev": "docs/going-out/week-06-vocational.md",
    "next": "docs/going-out/week-08-discernment.md"
  },
  "docs/going-out/week-08-discernment.md": {
    "seriesId": "going-out",
    "seriesName": "Going Out",
    "edition": "v3",
    "title": "Week 8 — Specific Missional Engagement",
    "indexPath": "docs/going-out/index.md",
    "prev": "docs/going-out/week-07-third-place.md",
    "next": "docs/going-out/week-09-body-sent-beyond.md"
  },
  "docs/going-out/week-09-body-sent-beyond.md": {
    "seriesId": "going-out",
    "seriesName": "Going Out",
    "edition": "v3",
    "title": "Week 9 — The Body Sent Beyond",
    "indexPath": "docs/going-out/index.md",
    "prev": "docs/going-out/week-08-discernment.md",
    "next": "docs/going-out/week-10-what-going-out-produced.md"
  },
  "docs/going-out/week-10-what-going-out-produced.md": {
    "seriesId": "going-out",
    "seriesName": "Going Out",
    "edition": "v3",
    "title": "Week 10 — What Going Out Produced",
    "indexPath": "docs/going-out/index.md",
    "prev": "docs/going-out/week-09-body-sent-beyond.md",
    "next": "docs/going-out/week-11-cohort-lands.md"
  },
  "docs/going-out/week-11-cohort-lands.md": {
    "seriesId": "going-out",
    "seriesName": "Going Out",
    "edition": "v3",
    "title": "Week 11 — Where the Cohort Lands as a Body",
    "indexPath": "docs/going-out/index.md",
    "prev": "docs/going-out/week-10-what-going-out-produced.md",
    "next": "docs/going-out/week-12-long-obedience.md"
  },
  "docs/going-out/week-12-long-obedience.md": {
    "seriesId": "going-out",
    "seriesName": "Going Out",
    "edition": "v3",
    "title": "Week 12 — Sending Into the Long Obedience",
    "indexPath": "docs/going-out/index.md",
    "prev": "docs/going-out/week-11-cohort-lands.md",
    "next": "docs/going-out/CHANGELOG.md"
  },
  "docs/going-out/CHANGELOG.md": {
    "seriesId": "going-out",
    "seriesName": "Going Out",
    "edition": "v3",
    "title": "Change Log",
    "indexPath": "docs/going-out/index.md",
    "prev": "docs/going-out/week-12-long-obedience.md"
  },
  "docs/shared/index.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Shared participant materials",
    "indexPath": "docs/shared/index.md",
    "next": "docs/shared/family-conversation-cards.md"
  },
  "docs/shared/family-conversation-cards.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Family Conversation Cards",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/index.md",
    "next": "docs/shared/interrogating-reality-card.md"
  },
  "docs/shared/interrogating-reality-card.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Interrogating Reality Card",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/family-conversation-cards.md",
    "next": "docs/shared/personal-heart-journal.md"
  },
  "docs/shared/personal-heart-journal.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Personal Heart Journal",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/interrogating-reality-card.md",
    "next": "docs/shared/proapt-card.md"
  },
  "docs/shared/proapt-card.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "PROAPT Card",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/personal-heart-journal.md",
    "next": "docs/shared/reading-list.md"
  },
  "docs/shared/reading-list.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Reading List",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/proapt-card.md",
    "next": "docs/shared/rhythm-card.md"
  },
  "docs/shared/rhythm-card.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Rhythm Card",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/reading-list.md"
  }
};
