// manifest.js — GENERATED by tools/build-manifest.mjs. Do not hand-edit.
window.SITE = {
  "title": "Fellowship of the Heart",
  "subtitle": "Evening · CCA Pilot · Adult",
  "envLabel": "DEV",
  "license": {
    "label": "CC BY-SA 4.0",
    "url": "https://creativecommons.org/licenses/by-sa/4.0/"
  },
  "repo": "https://github.com/jgtittle-ministries/fellowship-of-the-heart-pilot-at-cca-dev"
};

window.SERIES = [
  {
    "id": "index",
    "kind": "page",
    "name": "Home",
    "path": "docs/index.md"
  },
  {
    "id": "start-here",
    "kind": "page",
    "name": "Start here",
    "path": "docs/start-here.md"
  },
  {
    "id": "evening",
    "kind": "series",
    "name": "FotH Evening",
    "folder": "docs/evening",
    "edition": "v1",
    "index": "docs/evening/index.md",
    "chapters": [
      {
        "path": "docs/evening/index.md",
        "title": "FotH Evening",
        "edition": "v1"
      },
      {
        "path": "docs/evening/handbook.md",
        "title": "The Evening Handbook",
        "edition": "v1"
      },
      {
        "path": "docs/evening/session-01-welcome-to-the-journey.md",
        "title": "Sessions 1–2 — Welcome to the Journey · The Soil of Your Heart",
        "edition": "v1"
      },
      {
        "path": "docs/evening/session-03-04-telling-your-story.md",
        "title": "Sessions 3–4 — Telling Your Story",
        "edition": "v1"
      },
      {
        "path": "docs/evening/session-05-knowing-and-being-known.md",
        "title": "Session 5 — Knowing and Being Known",
        "edition": "v1"
      },
      {
        "path": "docs/evening/session-06-safe-and-brave-together.md",
        "title": "Session 6 — Safe and Brave Together",
        "edition": "v1"
      },
      {
        "path": "docs/evening/session-07-08-hearing-god-in-scripture.md",
        "title": "Sessions 7–8 — Hearing God in Scripture",
        "edition": "v1"
      },
      {
        "path": "docs/evening/CHANGELOG.md",
        "title": "Change Log",
        "edition": "v1"
      }
    ]
  },
  {
    "id": "cca",
    "kind": "series",
    "name": "CCA Pilot",
    "folder": "docs/cca",
    "edition": null,
    "index": "docs/cca/index.md",
    "chapters": [
      {
        "path": "docs/cca/index.md",
        "title": "The CCA Pilot"
      },
      {
        "path": "docs/getting-started/index.md",
        "title": "Getting Started",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/handbook.md",
        "title": "Companion Handbook",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/precohort-discernment-guide.md",
        "title": "Pre-Cohort Discernment Guide",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-01-welcome.md",
        "title": "Week 1 — Welcome to the Journey",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-02-soil.md",
        "title": "Week 2 — The Soil of Your Heart",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-03-story.md",
        "title": "Week 3 — Telling Your Story I",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-04-story-2.md",
        "title": "Week 4 — Telling Your Story II",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-05-known.md",
        "title": "Week 5 — Knowing and Being Known",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-06-brave.md",
        "title": "Week 6 — Safe and Brave Together",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-07-proapt.md",
        "title": "Week 7 — Hearing God in Scripture — PROAPT I",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-08-proapt-2.md",
        "title": "Week 8 — Hearing God — PROAPT II",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-09-garden.md",
        "title": "Week 9 — The Garden of Your Heart I",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-10-garden-2.md",
        "title": "Week 10 — The Garden of Your Heart II",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-11-doubts.md",
        "title": "Week 11 — Any Doubts?",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-12-return.md",
        "title": "Week 12 — The Return",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-13-mission.md",
        "title": "Week 13 — What Was Prepared for You",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-14-second-running-a.md",
        "title": "Week 14 — Second Running: Block A",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-15-rhythm.md",
        "title": "Week 15 — The Rhythm and the Four Questions",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-16-family-night.md",
        "title": "Week 16 — Family Conversation Night",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-17-float.md",
        "title": "Week 17 — The Float",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-18-return-2.md",
        "title": "Week 18 — The Return II",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-19-second-running-b.md",
        "title": "Week 19 — Second Running: Block B",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-20-long-walk.md",
        "title": "Week 20 — The Long Walk",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-21-sending.md",
        "title": "Week 21 — Sending and Blessing",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/week-22-commissioning.md",
        "title": "Week 22 — Commissioning the Companions",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/cca-2026-27-calendar.md",
        "title": "The CCA 2026-27 Dates",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/getting-started/CHANGELOG.md",
        "title": "Change Log",
        "group": "Getting Started · 22 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/going-deeper/index.md",
        "title": "Going Deeper",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/going-deeper/handbook.md",
        "title": "Companion Handbook",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/going-deeper/week-01-welcome-back.md",
        "title": "Week 1 — Welcome Back",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/going-deeper/week-02-soils.md",
        "title": "Week 2 — The Soils Re-Examined",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/going-deeper/week-03-knots.md",
        "title": "Week 3 — Knots and Lies",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/going-deeper/week-04-co-processing.md",
        "title": "Week 4 — Co-Processing in the Room",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/going-deeper/week-05-confession.md",
        "title": "Week 5 — Confession and Restoration, Deepened",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/going-deeper/week-06-proapt.md",
        "title": "Week 6 — PROAPT, Extended",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/going-deeper/week-07-corporate-listening.md",
        "title": "Week 7 — Corporate Listening Prayer",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/going-deeper/week-08-group-hears-itself.md",
        "title": "Week 8 — What the Group Hears About Itself",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/going-deeper/week-09-shadow-mission.md",
        "title": "Week 9 — The Shadow Mission",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/going-deeper/week-10-calling-discernment.md",
        "title": "Week 10 — Calling Discernment, Acts 13",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/going-deeper/week-11-where-is-our-cohort.md",
        "title": "Week 11 — Where Is Our Cohort",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/going-deeper/week-12-sending-and-bridge.md",
        "title": "Week 12 — Sending and Bridge",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/going-deeper/CHANGELOG.md",
        "title": "Change Log",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/going-out/index.md",
        "title": "Going Out",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/going-out/handbook.md",
        "title": "Companion Handbook",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/going-out/inviting-others-handbook.md",
        "title": "Inviting Others Handbook",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/going-out/week-01-welcome-back.md",
        "title": "Week 1 — Welcome Back — Returning to the Sent Body",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/going-out/week-02-body-sent.md",
        "title": "Week 2 — What It Means to Be Sent",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/going-out/week-03-where-sent.md",
        "title": "Week 3 — Where Am I Being Sent",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/going-out/week-04-daily-tells.md",
        "title": "Week 4 — The Daily Tells",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/going-out/week-05-household.md",
        "title": "Week 5 — The Household Witness",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/going-out/week-06-vocational.md",
        "title": "Week 6 — The Vocational Witness",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/going-out/week-07-third-place.md",
        "title": "Week 7 — The Third-Place Network",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/going-out/week-08-discernment.md",
        "title": "Week 8 — Specific Missional Engagement",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/going-out/week-09-body-sent-beyond.md",
        "title": "Week 9 — The Body Sent Beyond",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/going-out/week-10-what-going-out-produced.md",
        "title": "Week 10 — What Going Out Produced",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/going-out/week-11-cohort-lands.md",
        "title": "Week 11 — Where the Cohort Lands as a Body",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/going-out/week-12-long-obedience.md",
        "title": "Week 12 — Sending Into the Long Obedience",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/going-out/CHANGELOG.md",
        "title": "Change Log",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      }
    ]
  },
  {
    "id": "adult",
    "kind": "series",
    "name": "Adult FotH",
    "folder": "docs/adult",
    "edition": null,
    "index": "docs/adult/index.md",
    "chapters": [
      {
        "path": "docs/adult/index.md",
        "title": "Adult FotH"
      },
      {
        "path": "docs/adult/start-here.md",
        "title": "Start here — the adult year"
      },
      {
        "path": "docs/adult/leadership-year-handbook.md",
        "title": "Leadership Year Handbook"
      },
      {
        "path": "docs/adult/adult-register-key.md",
        "title": "Adult Register Key"
      },
      {
        "path": "docs/adult/getting-started/index.md",
        "title": "Getting Started",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/handbook.md",
        "title": "Companion Handbook",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/precohort-discernment-guide.md",
        "title": "Pre-Cohort Discernment Guide",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-01-welcome.md",
        "title": "Week 1 — Welcome to the Journey",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-02-soil.md",
        "title": "Week 2 — The Soil of Your Heart",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-03-story.md",
        "title": "Week 3 — Telling Your Story I",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-04-story-2.md",
        "title": "Week 4 — Telling Your Story II",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-05-known.md",
        "title": "Week 5 — Knowing and Being Known",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-05-practice-hold.md",
        "title": "Practice Hold I — Two Weeks, No Meetings",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-06-brave.md",
        "title": "Week 6 — Safe and Brave Together",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-07-proapt.md",
        "title": "Week 7 — Hearing God in Scripture — PROAPT I",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-08-proapt-2.md",
        "title": "Week 8 — Hearing God — PROAPT II",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-09-garden.md",
        "title": "Week 9 — The Garden of Your Heart I",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-10-garden-2.md",
        "title": "Week 10 — The Garden of Your Heart II",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-10-practice-hold.md",
        "title": "Practice Hold II — Two Weeks, No Meetings",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-11-doubts.md",
        "title": "Week 11 — Any Doubts?",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-12-mission.md",
        "title": "Week 12 — What Was Prepared for You",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-13-rhythm.md",
        "title": "Week 13 — The Rhythm and the Dry Season",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-14-sending.md",
        "title": "Week 14 — Sending and Blessing",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/week-15-commissioning.md",
        "title": "Week 15 — Commissioning the Companions",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/getting-started/CHANGELOG.md",
        "title": "Change Log",
        "group": "Getting Started · 15 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-deeper/index.md",
        "title": "Going Deeper",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/adult/going-deeper/handbook.md",
        "title": "Companion Handbook",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/adult/going-deeper/week-01-welcome-back.md",
        "title": "Week 1 — Welcome Back",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/adult/going-deeper/week-02-soils.md",
        "title": "Week 2 — The Soils Re-Examined",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/adult/going-deeper/week-03-knots.md",
        "title": "Week 3 — Knots and Lies",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/adult/going-deeper/week-04-co-processing.md",
        "title": "Week 4 — Co-Processing in the Room",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/adult/going-deeper/week-05-confession.md",
        "title": "Week 5 — Confession and Restoration, Deepened",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/adult/going-deeper/week-06-practice-hold.md",
        "title": "Practice Hold — Two Weeks, No Meetings",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/adult/going-deeper/week-06-proapt.md",
        "title": "Week 6 — PROAPT, Extended",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/adult/going-deeper/week-07-corporate-listening.md",
        "title": "Week 7 — Corporate Listening Prayer",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/adult/going-deeper/week-08-group-hears-itself.md",
        "title": "Week 8 — What the Group Hears About Itself",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/adult/going-deeper/week-09-shadow-mission.md",
        "title": "Week 9 — The Shadow Mission",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/adult/going-deeper/week-10-calling-discernment.md",
        "title": "Week 10 — Calling Discernment, Acts 13",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/adult/going-deeper/week-11-where-is-our-cohort.md",
        "title": "Week 11 — Where Is Our Cohort",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/adult/going-deeper/week-12-sending-and-bridge.md",
        "title": "Week 12 — Sending and Bridge",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/adult/going-deeper/CHANGELOG.md",
        "title": "Change Log",
        "group": "Going Deeper · 12 weeks",
        "edition": "v2"
      },
      {
        "path": "docs/adult/going-out/index.md",
        "title": "Going Out",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-out/handbook.md",
        "title": "Companion Handbook",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-out/inviting-others-handbook.md",
        "title": "Inviting Others Handbook",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-out/week-01-welcome-back.md",
        "title": "Week 1 — Welcome Back — Returning to the Sent Body",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-out/week-02-body-sent.md",
        "title": "Week 2 — What It Means to Be Sent",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-out/week-03-where-sent.md",
        "title": "Week 3 — Where Am I Being Sent",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-out/week-04-daily-tells.md",
        "title": "Week 4 — The Daily Tells",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-out/week-05-household.md",
        "title": "Week 5 — The Household Witness",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-out/week-06-vocational.md",
        "title": "Week 6 — The Vocational Witness",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-out/week-07-third-place.md",
        "title": "Week 7 — The Third-Place Network",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-out/week-08-discernment.md",
        "title": "Week 8 — Specific Missional Engagement",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-out/week-08-practice-hold.md",
        "title": "Practice Hold — Two Weeks, and the Cohort's Yes",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-out/week-09-body-sent-beyond.md",
        "title": "Week 9 — The Body Sent Beyond",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-out/week-10-what-going-out-produced.md",
        "title": "Week 10 — What Going Out Produced",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-out/week-11-cohort-lands.md",
        "title": "Week 11 — Where the Cohort Lands as a Body",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-out/week-12-long-obedience.md",
        "title": "Week 12 — Sending Into the Long Obedience",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      },
      {
        "path": "docs/adult/going-out/CHANGELOG.md",
        "title": "Change Log",
        "group": "Going Out · 12 weeks",
        "edition": "v3"
      }
    ]
  },
  {
    "id": "shared",
    "kind": "series",
    "name": "Shared materials",
    "folder": "docs/shared",
    "edition": null,
    "index": "docs/shared/index.md",
    "chapters": [
      {
        "path": "docs/shared/index.md",
        "title": "Shared participant materials"
      },
      {
        "path": "docs/shared/companions-and-coverings.md",
        "title": "Companions and Coverings"
      },
      {
        "path": "docs/shared/family-conversation-cards.md",
        "title": "Family Conversation Cards"
      },
      {
        "path": "docs/shared/interrogating-reality-card.md",
        "title": "Interrogating Reality Card"
      },
      {
        "path": "docs/shared/keeping-the-flame.md",
        "title": "Keeping the Flame"
      },
      {
        "path": "docs/shared/measurement-covenant.md",
        "title": "Measurement Covenant"
      },
      {
        "path": "docs/shared/path-home-card.md",
        "title": "Path Home Card"
      },
      {
        "path": "docs/shared/personal-heart-journal.md",
        "title": "Personal Heart Journal"
      },
      {
        "path": "docs/shared/proapt-card.md",
        "title": "PROAPT Card"
      },
      {
        "path": "docs/shared/proapt-what-each-step-is-for.md",
        "title": "PROAPT — What Each Step Is For"
      },
      {
        "path": "docs/shared/reading-list.md",
        "title": "Reading List"
      },
      {
        "path": "docs/shared/rhythm-card.md",
        "title": "Rhythm Card"
      },
      {
        "path": "docs/shared/signs-card.md",
        "title": "Signs Card"
      },
      {
        "path": "docs/shared/three-vital-signs.md",
        "title": "Three Vital Signs"
      },
      {
        "path": "docs/shared/watching-trust-grow.md",
        "title": "Watching Trust Grow"
      },
      {
        "path": "docs/shared/weekly-run-card.md",
        "title": "Weekly Run Card"
      }
    ]
  }
];

window.PATH_TO_INFO = {
  "docs/index.md": {
    "seriesId": "index",
    "seriesName": "Home",
    "title": "Home",
    "indexPath": "docs/index.md"
  },
  "docs/start-here.md": {
    "seriesId": "start-here",
    "seriesName": "Start here",
    "title": "Start here",
    "indexPath": "docs/start-here.md"
  },
  "docs/evening/index.md": {
    "seriesId": "evening",
    "seriesName": "FotH Evening",
    "edition": "v1",
    "title": "FotH Evening",
    "indexPath": "docs/evening/index.md",
    "next": "docs/evening/handbook.md"
  },
  "docs/evening/handbook.md": {
    "seriesId": "evening",
    "seriesName": "FotH Evening",
    "edition": "v1",
    "title": "The Evening Handbook",
    "indexPath": "docs/evening/index.md",
    "prev": "docs/evening/index.md",
    "next": "docs/evening/session-01-welcome-to-the-journey.md"
  },
  "docs/evening/session-01-welcome-to-the-journey.md": {
    "seriesId": "evening",
    "seriesName": "FotH Evening",
    "edition": "v1",
    "title": "Sessions 1–2 — Welcome to the Journey · The Soil of Your Heart",
    "indexPath": "docs/evening/index.md",
    "prev": "docs/evening/handbook.md",
    "next": "docs/evening/session-03-04-telling-your-story.md"
  },
  "docs/evening/session-03-04-telling-your-story.md": {
    "seriesId": "evening",
    "seriesName": "FotH Evening",
    "edition": "v1",
    "title": "Sessions 3–4 — Telling Your Story",
    "indexPath": "docs/evening/index.md",
    "prev": "docs/evening/session-01-welcome-to-the-journey.md",
    "next": "docs/evening/session-05-knowing-and-being-known.md"
  },
  "docs/evening/session-05-knowing-and-being-known.md": {
    "seriesId": "evening",
    "seriesName": "FotH Evening",
    "edition": "v1",
    "title": "Session 5 — Knowing and Being Known",
    "indexPath": "docs/evening/index.md",
    "prev": "docs/evening/session-03-04-telling-your-story.md",
    "next": "docs/evening/session-06-safe-and-brave-together.md"
  },
  "docs/evening/session-06-safe-and-brave-together.md": {
    "seriesId": "evening",
    "seriesName": "FotH Evening",
    "edition": "v1",
    "title": "Session 6 — Safe and Brave Together",
    "indexPath": "docs/evening/index.md",
    "prev": "docs/evening/session-05-knowing-and-being-known.md",
    "next": "docs/evening/session-07-08-hearing-god-in-scripture.md"
  },
  "docs/evening/session-07-08-hearing-god-in-scripture.md": {
    "seriesId": "evening",
    "seriesName": "FotH Evening",
    "edition": "v1",
    "title": "Sessions 7–8 — Hearing God in Scripture",
    "indexPath": "docs/evening/index.md",
    "prev": "docs/evening/session-06-safe-and-brave-together.md",
    "next": "docs/evening/CHANGELOG.md"
  },
  "docs/evening/CHANGELOG.md": {
    "seriesId": "evening",
    "seriesName": "FotH Evening",
    "edition": "v1",
    "title": "Change Log",
    "indexPath": "docs/evening/index.md",
    "prev": "docs/evening/session-07-08-hearing-god-in-scripture.md"
  },
  "docs/cca/index.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "title": "The CCA Pilot",
    "indexPath": "docs/cca/index.md",
    "next": "docs/getting-started/index.md"
  },
  "docs/getting-started/index.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Getting Started",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/cca/index.md",
    "next": "docs/getting-started/handbook.md"
  },
  "docs/getting-started/handbook.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Companion Handbook",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/index.md",
    "next": "docs/getting-started/precohort-discernment-guide.md"
  },
  "docs/getting-started/precohort-discernment-guide.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Pre-Cohort Discernment Guide",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/handbook.md",
    "next": "docs/getting-started/week-01-welcome.md"
  },
  "docs/getting-started/week-01-welcome.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 1 — Welcome to the Journey",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/precohort-discernment-guide.md",
    "next": "docs/getting-started/week-02-soil.md"
  },
  "docs/getting-started/week-02-soil.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 2 — The Soil of Your Heart",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-01-welcome.md",
    "next": "docs/getting-started/week-03-story.md"
  },
  "docs/getting-started/week-03-story.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 3 — Telling Your Story I",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-02-soil.md",
    "next": "docs/getting-started/week-04-story-2.md"
  },
  "docs/getting-started/week-04-story-2.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 4 — Telling Your Story II",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-03-story.md",
    "next": "docs/getting-started/week-05-known.md"
  },
  "docs/getting-started/week-05-known.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 5 — Knowing and Being Known",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-04-story-2.md",
    "next": "docs/getting-started/week-06-brave.md"
  },
  "docs/getting-started/week-06-brave.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 6 — Safe and Brave Together",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-05-known.md",
    "next": "docs/getting-started/week-07-proapt.md"
  },
  "docs/getting-started/week-07-proapt.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 7 — Hearing God in Scripture — PROAPT I",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-06-brave.md",
    "next": "docs/getting-started/week-08-proapt-2.md"
  },
  "docs/getting-started/week-08-proapt-2.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 8 — Hearing God — PROAPT II",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-07-proapt.md",
    "next": "docs/getting-started/week-09-garden.md"
  },
  "docs/getting-started/week-09-garden.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 9 — The Garden of Your Heart I",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-08-proapt-2.md",
    "next": "docs/getting-started/week-10-garden-2.md"
  },
  "docs/getting-started/week-10-garden-2.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 10 — The Garden of Your Heart II",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-09-garden.md",
    "next": "docs/getting-started/week-11-doubts.md"
  },
  "docs/getting-started/week-11-doubts.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 11 — Any Doubts?",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-10-garden-2.md",
    "next": "docs/getting-started/week-12-return.md"
  },
  "docs/getting-started/week-12-return.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 12 — The Return",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-11-doubts.md",
    "next": "docs/getting-started/week-13-mission.md"
  },
  "docs/getting-started/week-13-mission.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 13 — What Was Prepared for You",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-12-return.md",
    "next": "docs/getting-started/week-14-second-running-a.md"
  },
  "docs/getting-started/week-14-second-running-a.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 14 — Second Running: Block A",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-13-mission.md",
    "next": "docs/getting-started/week-15-rhythm.md"
  },
  "docs/getting-started/week-15-rhythm.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 15 — The Rhythm and the Four Questions",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-14-second-running-a.md",
    "next": "docs/getting-started/week-16-family-night.md"
  },
  "docs/getting-started/week-16-family-night.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 16 — Family Conversation Night",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-15-rhythm.md",
    "next": "docs/getting-started/week-17-float.md"
  },
  "docs/getting-started/week-17-float.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 17 — The Float",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-16-family-night.md",
    "next": "docs/getting-started/week-18-return-2.md"
  },
  "docs/getting-started/week-18-return-2.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 18 — The Return II",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-17-float.md",
    "next": "docs/getting-started/week-19-second-running-b.md"
  },
  "docs/getting-started/week-19-second-running-b.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 19 — Second Running: Block B",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-18-return-2.md",
    "next": "docs/getting-started/week-20-long-walk.md"
  },
  "docs/getting-started/week-20-long-walk.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 20 — The Long Walk",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-19-second-running-b.md",
    "next": "docs/getting-started/week-21-sending.md"
  },
  "docs/getting-started/week-21-sending.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 21 — Sending and Blessing",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-20-long-walk.md",
    "next": "docs/getting-started/week-22-commissioning.md"
  },
  "docs/getting-started/week-22-commissioning.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Week 22 — Commissioning the Companions",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-21-sending.md",
    "next": "docs/getting-started/cca-2026-27-calendar.md"
  },
  "docs/getting-started/cca-2026-27-calendar.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "The CCA 2026-27 Dates",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/week-22-commissioning.md",
    "next": "docs/getting-started/CHANGELOG.md"
  },
  "docs/getting-started/CHANGELOG.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Getting Started · 22 weeks",
    "title": "Change Log",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/cca-2026-27-calendar.md",
    "next": "docs/going-deeper/index.md"
  },
  "docs/going-deeper/index.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Going Deeper",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/getting-started/CHANGELOG.md",
    "next": "docs/going-deeper/handbook.md"
  },
  "docs/going-deeper/handbook.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Companion Handbook",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-deeper/index.md",
    "next": "docs/going-deeper/week-01-welcome-back.md"
  },
  "docs/going-deeper/week-01-welcome-back.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 1 — Welcome Back",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-deeper/handbook.md",
    "next": "docs/going-deeper/week-02-soils.md"
  },
  "docs/going-deeper/week-02-soils.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 2 — The Soils Re-Examined",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-deeper/week-01-welcome-back.md",
    "next": "docs/going-deeper/week-03-knots.md"
  },
  "docs/going-deeper/week-03-knots.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 3 — Knots and Lies",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-deeper/week-02-soils.md",
    "next": "docs/going-deeper/week-04-co-processing.md"
  },
  "docs/going-deeper/week-04-co-processing.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 4 — Co-Processing in the Room",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-deeper/week-03-knots.md",
    "next": "docs/going-deeper/week-05-confession.md"
  },
  "docs/going-deeper/week-05-confession.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 5 — Confession and Restoration, Deepened",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-deeper/week-04-co-processing.md",
    "next": "docs/going-deeper/week-06-proapt.md"
  },
  "docs/going-deeper/week-06-proapt.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 6 — PROAPT, Extended",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-deeper/week-05-confession.md",
    "next": "docs/going-deeper/week-07-corporate-listening.md"
  },
  "docs/going-deeper/week-07-corporate-listening.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 7 — Corporate Listening Prayer",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-deeper/week-06-proapt.md",
    "next": "docs/going-deeper/week-08-group-hears-itself.md"
  },
  "docs/going-deeper/week-08-group-hears-itself.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 8 — What the Group Hears About Itself",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-deeper/week-07-corporate-listening.md",
    "next": "docs/going-deeper/week-09-shadow-mission.md"
  },
  "docs/going-deeper/week-09-shadow-mission.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 9 — The Shadow Mission",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-deeper/week-08-group-hears-itself.md",
    "next": "docs/going-deeper/week-10-calling-discernment.md"
  },
  "docs/going-deeper/week-10-calling-discernment.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 10 — Calling Discernment, Acts 13",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-deeper/week-09-shadow-mission.md",
    "next": "docs/going-deeper/week-11-where-is-our-cohort.md"
  },
  "docs/going-deeper/week-11-where-is-our-cohort.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 11 — Where Is Our Cohort",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-deeper/week-10-calling-discernment.md",
    "next": "docs/going-deeper/week-12-sending-and-bridge.md"
  },
  "docs/going-deeper/week-12-sending-and-bridge.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 12 — Sending and Bridge",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-deeper/week-11-where-is-our-cohort.md",
    "next": "docs/going-deeper/CHANGELOG.md"
  },
  "docs/going-deeper/CHANGELOG.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Change Log",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-deeper/week-12-sending-and-bridge.md",
    "next": "docs/going-out/index.md"
  },
  "docs/going-out/index.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Going Out",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-deeper/CHANGELOG.md",
    "next": "docs/going-out/handbook.md"
  },
  "docs/going-out/handbook.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Companion Handbook",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-out/index.md",
    "next": "docs/going-out/inviting-others-handbook.md"
  },
  "docs/going-out/inviting-others-handbook.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Inviting Others Handbook",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-out/handbook.md",
    "next": "docs/going-out/week-01-welcome-back.md"
  },
  "docs/going-out/week-01-welcome-back.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 1 — Welcome Back — Returning to the Sent Body",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-out/inviting-others-handbook.md",
    "next": "docs/going-out/week-02-body-sent.md"
  },
  "docs/going-out/week-02-body-sent.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 2 — What It Means to Be Sent",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-out/week-01-welcome-back.md",
    "next": "docs/going-out/week-03-where-sent.md"
  },
  "docs/going-out/week-03-where-sent.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 3 — Where Am I Being Sent",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-out/week-02-body-sent.md",
    "next": "docs/going-out/week-04-daily-tells.md"
  },
  "docs/going-out/week-04-daily-tells.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 4 — The Daily Tells",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-out/week-03-where-sent.md",
    "next": "docs/going-out/week-05-household.md"
  },
  "docs/going-out/week-05-household.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 5 — The Household Witness",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-out/week-04-daily-tells.md",
    "next": "docs/going-out/week-06-vocational.md"
  },
  "docs/going-out/week-06-vocational.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 6 — The Vocational Witness",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-out/week-05-household.md",
    "next": "docs/going-out/week-07-third-place.md"
  },
  "docs/going-out/week-07-third-place.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 7 — The Third-Place Network",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-out/week-06-vocational.md",
    "next": "docs/going-out/week-08-discernment.md"
  },
  "docs/going-out/week-08-discernment.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 8 — Specific Missional Engagement",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-out/week-07-third-place.md",
    "next": "docs/going-out/week-09-body-sent-beyond.md"
  },
  "docs/going-out/week-09-body-sent-beyond.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 9 — The Body Sent Beyond",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-out/week-08-discernment.md",
    "next": "docs/going-out/week-10-what-going-out-produced.md"
  },
  "docs/going-out/week-10-what-going-out-produced.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 10 — What Going Out Produced",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-out/week-09-body-sent-beyond.md",
    "next": "docs/going-out/week-11-cohort-lands.md"
  },
  "docs/going-out/week-11-cohort-lands.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 11 — Where the Cohort Lands as a Body",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-out/week-10-what-going-out-produced.md",
    "next": "docs/going-out/week-12-long-obedience.md"
  },
  "docs/going-out/week-12-long-obedience.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 12 — Sending Into the Long Obedience",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-out/week-11-cohort-lands.md",
    "next": "docs/going-out/CHANGELOG.md"
  },
  "docs/going-out/CHANGELOG.md": {
    "seriesId": "cca",
    "seriesName": "CCA Pilot",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Change Log",
    "indexPath": "docs/cca/index.md",
    "prev": "docs/going-out/week-12-long-obedience.md"
  },
  "docs/adult/index.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "title": "Adult FotH",
    "indexPath": "docs/adult/index.md",
    "next": "docs/adult/start-here.md"
  },
  "docs/adult/start-here.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "title": "Start here — the adult year",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/index.md",
    "next": "docs/adult/leadership-year-handbook.md"
  },
  "docs/adult/leadership-year-handbook.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "title": "Leadership Year Handbook",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/start-here.md",
    "next": "docs/adult/adult-register-key.md"
  },
  "docs/adult/adult-register-key.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "title": "Adult Register Key",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/leadership-year-handbook.md",
    "next": "docs/adult/getting-started/index.md"
  },
  "docs/adult/getting-started/index.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Getting Started",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/adult-register-key.md",
    "next": "docs/adult/getting-started/handbook.md"
  },
  "docs/adult/getting-started/handbook.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Companion Handbook",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/index.md",
    "next": "docs/adult/getting-started/precohort-discernment-guide.md"
  },
  "docs/adult/getting-started/precohort-discernment-guide.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Pre-Cohort Discernment Guide",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/handbook.md",
    "next": "docs/adult/getting-started/week-01-welcome.md"
  },
  "docs/adult/getting-started/week-01-welcome.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Week 1 — Welcome to the Journey",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/precohort-discernment-guide.md",
    "next": "docs/adult/getting-started/week-02-soil.md"
  },
  "docs/adult/getting-started/week-02-soil.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Week 2 — The Soil of Your Heart",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-01-welcome.md",
    "next": "docs/adult/getting-started/week-03-story.md"
  },
  "docs/adult/getting-started/week-03-story.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Week 3 — Telling Your Story I",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-02-soil.md",
    "next": "docs/adult/getting-started/week-04-story-2.md"
  },
  "docs/adult/getting-started/week-04-story-2.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Week 4 — Telling Your Story II",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-03-story.md",
    "next": "docs/adult/getting-started/week-05-known.md"
  },
  "docs/adult/getting-started/week-05-known.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Week 5 — Knowing and Being Known",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-04-story-2.md",
    "next": "docs/adult/getting-started/week-05-practice-hold.md"
  },
  "docs/adult/getting-started/week-05-practice-hold.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Practice Hold I — Two Weeks, No Meetings",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-05-known.md",
    "next": "docs/adult/getting-started/week-06-brave.md"
  },
  "docs/adult/getting-started/week-06-brave.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Week 6 — Safe and Brave Together",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-05-practice-hold.md",
    "next": "docs/adult/getting-started/week-07-proapt.md"
  },
  "docs/adult/getting-started/week-07-proapt.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Week 7 — Hearing God in Scripture — PROAPT I",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-06-brave.md",
    "next": "docs/adult/getting-started/week-08-proapt-2.md"
  },
  "docs/adult/getting-started/week-08-proapt-2.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Week 8 — Hearing God — PROAPT II",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-07-proapt.md",
    "next": "docs/adult/getting-started/week-09-garden.md"
  },
  "docs/adult/getting-started/week-09-garden.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Week 9 — The Garden of Your Heart I",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-08-proapt-2.md",
    "next": "docs/adult/getting-started/week-10-garden-2.md"
  },
  "docs/adult/getting-started/week-10-garden-2.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Week 10 — The Garden of Your Heart II",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-09-garden.md",
    "next": "docs/adult/getting-started/week-10-practice-hold.md"
  },
  "docs/adult/getting-started/week-10-practice-hold.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Practice Hold II — Two Weeks, No Meetings",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-10-garden-2.md",
    "next": "docs/adult/getting-started/week-11-doubts.md"
  },
  "docs/adult/getting-started/week-11-doubts.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Week 11 — Any Doubts?",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-10-practice-hold.md",
    "next": "docs/adult/getting-started/week-12-mission.md"
  },
  "docs/adult/getting-started/week-12-mission.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Week 12 — What Was Prepared for You",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-11-doubts.md",
    "next": "docs/adult/getting-started/week-13-rhythm.md"
  },
  "docs/adult/getting-started/week-13-rhythm.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Week 13 — The Rhythm and the Dry Season",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-12-mission.md",
    "next": "docs/adult/getting-started/week-14-sending.md"
  },
  "docs/adult/getting-started/week-14-sending.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Week 14 — Sending and Blessing",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-13-rhythm.md",
    "next": "docs/adult/getting-started/week-15-commissioning.md"
  },
  "docs/adult/getting-started/week-15-commissioning.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Week 15 — Commissioning the Companions",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-14-sending.md",
    "next": "docs/adult/getting-started/CHANGELOG.md"
  },
  "docs/adult/getting-started/CHANGELOG.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Getting Started · 15 weeks",
    "title": "Change Log",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/week-15-commissioning.md",
    "next": "docs/adult/going-deeper/index.md"
  },
  "docs/adult/going-deeper/index.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Going Deeper",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/getting-started/CHANGELOG.md",
    "next": "docs/adult/going-deeper/handbook.md"
  },
  "docs/adult/going-deeper/handbook.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Companion Handbook",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-deeper/index.md",
    "next": "docs/adult/going-deeper/week-01-welcome-back.md"
  },
  "docs/adult/going-deeper/week-01-welcome-back.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 1 — Welcome Back",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-deeper/handbook.md",
    "next": "docs/adult/going-deeper/week-02-soils.md"
  },
  "docs/adult/going-deeper/week-02-soils.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 2 — The Soils Re-Examined",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-deeper/week-01-welcome-back.md",
    "next": "docs/adult/going-deeper/week-03-knots.md"
  },
  "docs/adult/going-deeper/week-03-knots.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 3 — Knots and Lies",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-deeper/week-02-soils.md",
    "next": "docs/adult/going-deeper/week-04-co-processing.md"
  },
  "docs/adult/going-deeper/week-04-co-processing.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 4 — Co-Processing in the Room",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-deeper/week-03-knots.md",
    "next": "docs/adult/going-deeper/week-05-confession.md"
  },
  "docs/adult/going-deeper/week-05-confession.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 5 — Confession and Restoration, Deepened",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-deeper/week-04-co-processing.md",
    "next": "docs/adult/going-deeper/week-06-practice-hold.md"
  },
  "docs/adult/going-deeper/week-06-practice-hold.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Practice Hold — Two Weeks, No Meetings",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-deeper/week-05-confession.md",
    "next": "docs/adult/going-deeper/week-06-proapt.md"
  },
  "docs/adult/going-deeper/week-06-proapt.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 6 — PROAPT, Extended",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-deeper/week-06-practice-hold.md",
    "next": "docs/adult/going-deeper/week-07-corporate-listening.md"
  },
  "docs/adult/going-deeper/week-07-corporate-listening.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 7 — Corporate Listening Prayer",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-deeper/week-06-proapt.md",
    "next": "docs/adult/going-deeper/week-08-group-hears-itself.md"
  },
  "docs/adult/going-deeper/week-08-group-hears-itself.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 8 — What the Group Hears About Itself",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-deeper/week-07-corporate-listening.md",
    "next": "docs/adult/going-deeper/week-09-shadow-mission.md"
  },
  "docs/adult/going-deeper/week-09-shadow-mission.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 9 — The Shadow Mission",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-deeper/week-08-group-hears-itself.md",
    "next": "docs/adult/going-deeper/week-10-calling-discernment.md"
  },
  "docs/adult/going-deeper/week-10-calling-discernment.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 10 — Calling Discernment, Acts 13",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-deeper/week-09-shadow-mission.md",
    "next": "docs/adult/going-deeper/week-11-where-is-our-cohort.md"
  },
  "docs/adult/going-deeper/week-11-where-is-our-cohort.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 11 — Where Is Our Cohort",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-deeper/week-10-calling-discernment.md",
    "next": "docs/adult/going-deeper/week-12-sending-and-bridge.md"
  },
  "docs/adult/going-deeper/week-12-sending-and-bridge.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Week 12 — Sending and Bridge",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-deeper/week-11-where-is-our-cohort.md",
    "next": "docs/adult/going-deeper/CHANGELOG.md"
  },
  "docs/adult/going-deeper/CHANGELOG.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v2",
    "group": "Going Deeper · 12 weeks",
    "title": "Change Log",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-deeper/week-12-sending-and-bridge.md",
    "next": "docs/adult/going-out/index.md"
  },
  "docs/adult/going-out/index.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Going Out",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-deeper/CHANGELOG.md",
    "next": "docs/adult/going-out/handbook.md"
  },
  "docs/adult/going-out/handbook.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Companion Handbook",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-out/index.md",
    "next": "docs/adult/going-out/inviting-others-handbook.md"
  },
  "docs/adult/going-out/inviting-others-handbook.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Inviting Others Handbook",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-out/handbook.md",
    "next": "docs/adult/going-out/week-01-welcome-back.md"
  },
  "docs/adult/going-out/week-01-welcome-back.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 1 — Welcome Back — Returning to the Sent Body",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-out/inviting-others-handbook.md",
    "next": "docs/adult/going-out/week-02-body-sent.md"
  },
  "docs/adult/going-out/week-02-body-sent.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 2 — What It Means to Be Sent",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-out/week-01-welcome-back.md",
    "next": "docs/adult/going-out/week-03-where-sent.md"
  },
  "docs/adult/going-out/week-03-where-sent.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 3 — Where Am I Being Sent",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-out/week-02-body-sent.md",
    "next": "docs/adult/going-out/week-04-daily-tells.md"
  },
  "docs/adult/going-out/week-04-daily-tells.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 4 — The Daily Tells",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-out/week-03-where-sent.md",
    "next": "docs/adult/going-out/week-05-household.md"
  },
  "docs/adult/going-out/week-05-household.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 5 — The Household Witness",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-out/week-04-daily-tells.md",
    "next": "docs/adult/going-out/week-06-vocational.md"
  },
  "docs/adult/going-out/week-06-vocational.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 6 — The Vocational Witness",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-out/week-05-household.md",
    "next": "docs/adult/going-out/week-07-third-place.md"
  },
  "docs/adult/going-out/week-07-third-place.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 7 — The Third-Place Network",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-out/week-06-vocational.md",
    "next": "docs/adult/going-out/week-08-discernment.md"
  },
  "docs/adult/going-out/week-08-discernment.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 8 — Specific Missional Engagement",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-out/week-07-third-place.md",
    "next": "docs/adult/going-out/week-08-practice-hold.md"
  },
  "docs/adult/going-out/week-08-practice-hold.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Practice Hold — Two Weeks, and the Cohort's Yes",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-out/week-08-discernment.md",
    "next": "docs/adult/going-out/week-09-body-sent-beyond.md"
  },
  "docs/adult/going-out/week-09-body-sent-beyond.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 9 — The Body Sent Beyond",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-out/week-08-practice-hold.md",
    "next": "docs/adult/going-out/week-10-what-going-out-produced.md"
  },
  "docs/adult/going-out/week-10-what-going-out-produced.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 10 — What Going Out Produced",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-out/week-09-body-sent-beyond.md",
    "next": "docs/adult/going-out/week-11-cohort-lands.md"
  },
  "docs/adult/going-out/week-11-cohort-lands.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 11 — Where the Cohort Lands as a Body",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-out/week-10-what-going-out-produced.md",
    "next": "docs/adult/going-out/week-12-long-obedience.md"
  },
  "docs/adult/going-out/week-12-long-obedience.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Week 12 — Sending Into the Long Obedience",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-out/week-11-cohort-lands.md",
    "next": "docs/adult/going-out/CHANGELOG.md"
  },
  "docs/adult/going-out/CHANGELOG.md": {
    "seriesId": "adult",
    "seriesName": "Adult FotH",
    "edition": "v3",
    "group": "Going Out · 12 weeks",
    "title": "Change Log",
    "indexPath": "docs/adult/index.md",
    "prev": "docs/adult/going-out/week-12-long-obedience.md"
  },
  "docs/shared/index.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Shared participant materials",
    "indexPath": "docs/shared/index.md",
    "next": "docs/shared/companions-and-coverings.md"
  },
  "docs/shared/companions-and-coverings.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Companions and Coverings",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/index.md",
    "next": "docs/shared/family-conversation-cards.md"
  },
  "docs/shared/family-conversation-cards.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Family Conversation Cards",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/companions-and-coverings.md",
    "next": "docs/shared/interrogating-reality-card.md"
  },
  "docs/shared/interrogating-reality-card.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Interrogating Reality Card",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/family-conversation-cards.md",
    "next": "docs/shared/keeping-the-flame.md"
  },
  "docs/shared/keeping-the-flame.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Keeping the Flame",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/interrogating-reality-card.md",
    "next": "docs/shared/measurement-covenant.md"
  },
  "docs/shared/measurement-covenant.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Measurement Covenant",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/keeping-the-flame.md",
    "next": "docs/shared/path-home-card.md"
  },
  "docs/shared/path-home-card.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Path Home Card",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/measurement-covenant.md",
    "next": "docs/shared/personal-heart-journal.md"
  },
  "docs/shared/personal-heart-journal.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Personal Heart Journal",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/path-home-card.md",
    "next": "docs/shared/proapt-card.md"
  },
  "docs/shared/proapt-card.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "PROAPT Card",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/personal-heart-journal.md",
    "next": "docs/shared/proapt-what-each-step-is-for.md"
  },
  "docs/shared/proapt-what-each-step-is-for.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "PROAPT — What Each Step Is For",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/proapt-card.md",
    "next": "docs/shared/reading-list.md"
  },
  "docs/shared/reading-list.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Reading List",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/proapt-what-each-step-is-for.md",
    "next": "docs/shared/rhythm-card.md"
  },
  "docs/shared/rhythm-card.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Rhythm Card",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/reading-list.md",
    "next": "docs/shared/signs-card.md"
  },
  "docs/shared/signs-card.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Signs Card",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/rhythm-card.md",
    "next": "docs/shared/three-vital-signs.md"
  },
  "docs/shared/three-vital-signs.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Three Vital Signs",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/signs-card.md",
    "next": "docs/shared/watching-trust-grow.md"
  },
  "docs/shared/watching-trust-grow.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Watching Trust Grow",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/three-vital-signs.md",
    "next": "docs/shared/weekly-run-card.md"
  },
  "docs/shared/weekly-run-card.md": {
    "seriesId": "shared",
    "seriesName": "Shared materials",
    "title": "Weekly Run Card",
    "indexPath": "docs/shared/index.md",
    "prev": "docs/shared/watching-trust-grow.md"
  }
};
